// Generates src/version.ts from package.json so the engine version embedded in
// every valuation report has a single source of truth (review finding N-19).
// Runs as `prebuild` / `pretest`; the generated file is committed so that
// `tsc` / `vitest` work without the hook as well.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
const content = `// Generated by tools/gen-version.mjs from package.json – do not edit.\nexport const PACKAGE_NAME = ${JSON.stringify(pkg.name)};\nexport const PACKAGE_VERSION = ${JSON.stringify(pkg.version)};\n`;
const target = resolve(root, "src", "version.ts");
let current = "";
try {
  current = readFileSync(target, "utf8");
} catch {
  current = "";
}
if (current !== content) {
  writeFileSync(target, content);
  console.warn(`gen-version: wrote src/version.ts (${pkg.name}@${pkg.version})`);
}
