/**
 * Public surface of `@deriva/pricing-core` (ADR-024). Every module is
 * re-exported with an explicit, curated name list – no `export *` – so the
 * public API is readable here and every addition is a visible diff (N4-03,
 * round 5). Since round 6 (N6-01) the list is genuinely curated: implementation
 * helpers (root finding, interpolation coefficients, leg-pricing internals,
 * vol-quotation conversion, exposure engines, the `nextTradeId` module counter,
 * the indicative sample vol surfaces, …) live behind the second entry point
 * `@deriva/pricing-core/internal` (`src/internal.ts`), which carries no SemVer
 * promise. Names the API or the Web app import are always public –
 * `node tools/gen-index.mjs --check` verifies that every module export is
 * reachable through exactly one entry point and that every app import is on
 * this list (`src/surface.test.ts`). Values are listed first, `type` exports
 * last.
 */
// Errors, formatting, version
export { PricingError, isPricingError, type PricingErrorCode } from "./errors.js";
export { formatDateDe, formatDateTimeDe, formatDe, formatPctDe } from "./format.js";
export { PACKAGE_NAME, PACKAGE_VERSION } from "./version.js";
// Math (public vocabulary only – the algorithms live in `./internal`)
export { type InterpolationMethod } from "./math/interpolation.js";
// Dates
export {
  addDays,
  addMonths,
  addTenor,
  addYears,
  compareDates,
  dayOfWeek,
  daysInMonth,
  endOfMonth,
  fromYMD,
  immDate,
  isEndOfMonth,
  isLeapYear,
  isWeekend,
  nextImmDate,
  parseISO,
  parseTenor,
  tenorInMonths,
  tenorToString,
  toISO,
  toYMD,
  today,
  type SerialDate,
  type Tenor,
  type TenorUnit,
} from "./dates/date.js";
export {
  CustomCalendar,
  JointCalendar,
  addBusinessDays,
  adjust,
  advance,
  businessDaysBetween,
  clearCalendarHolidays,
  easterSunday,
  getCalendar,
  hasCalendarHolidayFeed,
  isBusinessDay,
  registerCalendar,
  registerCalendarHolidays,
  type BusinessDayConvention,
  type Calendar,
  type CalendarId,
} from "./dates/calendar.js";
export { dayCount, normalizeDayCount, yearFraction, type DayCountConvention, type YearFractionContext } from "./dates/daycount.js";
export {
  MAX_PERIODS,
  buildSchedule,
  estimatePeriodCount,
  frequencyPerYear,
  frequencyTenorOf,
  type Frequency,
  type RollConvention,
  type Schedule,
  type ScheduleParams,
  type SchedulePeriod,
  type StubType,
} from "./dates/schedule.js";
// Curves & market
export {
  InterpolatedCurve,
  curveSource,
  flatCurve,
  type Curve,
  type CurveExtrapolation,
  type CurveJson,
  type CurveNode,
  type CurveSource,
  type ForwardJump,
  type InterpolatedCurveOptions,
} from "./curves/curve.js";
export {
  RATE_INDICES,
  SWAP_CONVENTIONS,
  getIndex,
  getSwapConventions,
  knownCurrencies,
  knownIndices,
  registerRateIndex,
  registerSwapConventions,
  type RateIndex,
  type SwapConventions,
} from "./curves/index-definitions.js";
export {
  bootstrapCurve,
  bootstrapCurves,
  bumpQuote,
  quoteDates,
  quoteLabel,
  spotDate,
  type BasisSwapQuote,
  type BootstrapResult,
  type BootstrapSpec,
  type CurveBuildSpec,
  type CurveQuote,
  type FutureQuote,
  type FxSwapPointsQuote,
  type XccyBasisQuote,
} from "./curves/bootstrap.js";
export {
  collateralCurveWarnings,
  getCurve,
  getDiscountCurve,
  getFixing,
  getFxFixing,
  getFxSpot,
  hasCollateralCurve,
  normalizeFxPair,
  withCurves,
  type Fixing,
  type FxFixing,
  type FxSpot,
  type MarketContext,
  type MissingFixingPolicy,
} from "./market/market-context.js";
export { currencyCalendar, fxPairCalendar, fxRateAtValuationDate, fxSpotDate, fxSpotDateFrom, fxSpotLag } from "./market/fx-spot.js";
export {
  SAMPLE_CURVE_IDS,
  SAMPLE_FIXINGS,
  SAMPLE_QUOTES,
  buildSampleMarket,
  sampleBootstrapSpecs,
  sampleFixings,
  type SampleMarketQuotes,
} from "./market/sample-market.js";
// Models
export {
  bachelier,
  bachelierGreeks,
  black76,
  black76Greeks,
  convertIrVol,
  impliedBlackVol,
  impliedNormalVol,
  lognormalToNormalVol,
  normalToLognormalVol,
  shiftedBlack76,
  type IrVolQuotation,
  type OptionGreeks,
  type OptionType,
} from "./models/black.js";
export {
  fxBarrier,
  fxDigital,
  fxExoticGreeks,
  garmanKohlhagen,
  impliedFxVol,
  strikeFromForwardDelta,
  type BarrierType,
  type FxBarrierInputs,
  type FxExoticGreeks,
  type FxOptionInputs,
  type FxOptionResult,
} from "./models/garman-kohlhagen.js";
export { sabrAlphaFromAtm, sabrLognormalVol, sabrNormalVol, type SabrParams } from "./models/sabr.js";
export {
  capletVol,
  sabrParamsAt,
  shiftCapletSurface,
  shiftSwaptionSurface,
  swaptionAtmVol,
  swaptionVol,
  type CapletVolSurface,
  type SwaptionVolSurface,
  type VolType,
} from "./models/vol-surfaces.js";
export {
  brokerStrangleFromSmile,
  fxAtmVol,
  fxDeltaFromMoneyness,
  fxMoneynessFromDelta,
  fxStrikeFromDelta,
  fxVolAtDelta,
  fxVolAtStrike,
  shiftFxSurface,
  shiftFxSurfaceRow,
  smileStrangleFromBroker,
  smileVols,
  type FxDeltaConvention,
  type FxSmileComponent,
  type FxSmileContext,
  type FxSmileInterpolation,
  type FxStrangleType,
  type FxVolSurface,
  type SmilePoint,
} from "./models/fx-vol-surface.js";
// Instruments & pricing
export {
  type CapFloor,
  type Cashflow,
  type CrossCurrencySwap,
  type FixedLeg,
  type FloatLeg,
  type ForwardRateAgreement,
  type FxForward,
  type FxOption,
  type FxSwap,
  type InterestRateSwap,
  type LegBase,
  type LegResult,
  type PayReceive,
  type PricingResult,
  type SwapLeg,
  type Swaption,
  type Trade,
  type TradeBase,
  type TradeType,
} from "./instruments/types.js";
export {
  DEFAULT_AVAILABLE_INDICES,
  annuityAmortisation,
  annuityAmortisationSchedule,
  defaultCcsCollateralCurrency,
  fraIndexForPeriod,
  linearAmortisation,
  makeAmortisingSwap,
  makeBasisSwap,
  makeCapFloor,
  makeCrossCurrencySwap,
  makeFra,
  makeFxForward,
  makeFxOption,
  makeFxSwap,
  makeImmSwap,
  makeSwaption,
  makeVanillaSwap,
  type CrossCurrencySwapParams,
  type VanillaSwapParams,
} from "./instruments/builders.js";
export {
  TRADE_TYPE_LABELS_DE,
  barrierTypeLabelDe,
  bdcLabelDe,
  cashSettlementLabelDe,
  fxAtmConventionLabelDe,
  fxDeltaConventionLabelDe,
  irModelLabelDe,
  stubLabelDe,
  tradeTypeLabelDe,
  volTypeLabelDe,
  xvaMethodLabelDe,
} from "./instruments/labels.js";
export { embeddedOptionLegs, hasOptionality, tradeIndexNames, tradeMaturityDate } from "./instruments/trade-dates.js";
export { priceCrossCurrencySwap, priceInterestRateSwap, type SwapAnalytics } from "./pricing/swap-pricer.js";
export { priceFra } from "./pricing/fra-pricer.js";
export { priceCapFloor } from "./pricing/capfloor-pricer.js";
export { priceSwaption } from "./pricing/swaption-pricer.js";
export { UPFRONT_LEG_TYPE } from "./pricing/upfront.js";
export {
  BARRIER_STATE_UNKNOWN_PREFIX,
  EXPIRED_PREFIX,
  EXPIRES_TODAY_PREFIX,
  MISSING_FX_FIXING_PREFIX,
  SETTLES_TODAY_PREFIX,
  fxForwardRate,
  fxOptionLifecycle,
  priceFxForward,
  priceFxOption,
  priceFxSwap,
  splitPair,
  type BarrierState,
  type FxOptionLifecycle,
} from "./pricing/fx-pricer.js";
export { assertValidTrade, pricePortfolio, priceTrade, tradeCurrencies, validateTrade } from "./pricing/price.js";
// Risk & XVA
export {
  computeRisk,
  computeTheta,
  parRisk,
  parRiskPortfolio,
  relevantCurveIds,
  rollMarket,
  rollMarketForward,
  shiftCurvesParallel,
  shiftFxSpots,
  tradeCurveIds,
  vegaBuckets,
  type BucketedDelta,
  type ParRiskBucket,
  type ParRiskCurve,
  type ParRiskOptions,
  type ParRiskReport,
  type ParRiskSpecs,
  type RiskReport,
  type ThetaDetail,
  type VegaBucket,
  type VegaBucketOptions,
  type VegaBucketReport,
} from "./risk/sensitivities.js";
export {
  HISTORICAL_SCENARIOS,
  STANDARD_SCENARIOS,
  applyScenario,
  irVolShiftFor,
  runScenarios,
  scenarioGrid,
  type CurveShift,
  type IrVolShift,
  type ScenarioDefinition,
  type ScenarioResult,
} from "./risk/scenarios.js";
export {
  CDS_PREMIUM_ACCRUAL_PER_YEAR,
  assertValidCreditInputs,
  bootstrapHazardCurve,
  computeXva,
  flatHazardCurve,
  hazardFromSpread,
  marginalPd,
  survivalProbability,
  validateCreditInputs,
  type CreditInputs,
  type ExposurePoint,
  type HazardBootstrapOptions,
  type HazardCurve,
  type XvaResult,
} from "./xva/cva.js";
// Reporting
export {
  ENGINE_VERSION,
  buildValuationReport,
  cashflowTable,
  costTransparencyFor,
  hashString,
  ifrs13Level,
  marketSnapshotId,
  methodologyFor,
  stableStringify,
  toCsv,
  type CsvOptions,
  type MarketSnapshotIdOptions,
  type ReportPerspective,
  type ValuationGovernance,
  type ValuationReport,
  type ValuationReportOptions,
} from "./reporting/valuation-report.js";
export { deserializeMarket, serializeMarket, validateMarket, type MarketSnapshotJson } from "./market/snapshot.js";
export { VOL_IMPLAUSIBLE_PREFIX, VOL_PLAUSIBILITY, validateVolSurfaces, volSurfaceWarnings, type VolSurfacesInput } from "./market/vol-validation.js";
export {
  EMIR_CSV_HEADER,
  emirBoolean,
  emirCsv,
  emirDelta,
  emirValuationRecord,
  emirValuationTimestamp,
  type EmirBoolean,
  type EmirCleared,
  type EmirClearingObligation,
  type EmirRecordOptions,
  type EmirValuationRecord,
} from "./reporting/emir.js";
export {
  generateConfirmation,
  generateKid,
  generateSuitabilityStatement,
  generateTermsheet,
  summaryRiskIndicator,
  toMarkdown,
  type ConfirmationParties,
  type DocumentSection,
  type GeneratedDocument,
  type GeneratedDocumentKind,
  type KidOptions,
  type MasterAgreementRef,
  type SuitabilityInputs,
} from "./reporting/documents.js";
export {
  buildPortfolioReport,
  portfolioReportToMarkdown,
  type PortfolioAggregate,
  type PortfolioReport,
  type PortfolioReportLine,
  type PortfolioReportOptions,
} from "./reporting/portfolio-report.js";
export {
  DEFAULT_EFFECTIVENESS_BAND,
  DEFAULT_MIN_R2,
  MIN_ABS_DELTA,
  criticalTermsMatch,
  dollarOffset,
  hedgeEffectivenessReport,
  hgbSplit,
  hypotheticalDerivative,
  ifrs9Split,
  intrinsicValue,
  regressionTest,
  type AccountingFramework,
  type CostOfHedging,
  type CriticalTermCheck,
  type CriticalTermsResult,
  type DollarOffsetResult,
  type EffectivenessMethod,
  type HedgeDesignation,
  type HedgeEffectivenessReport,
  type HedgeRelationship,
  type HedgeReportOptions,
  type HedgeType,
  type HedgedItem,
  type HedgedItemAmortisation,
  type HedgedItemKind,
  type HgbResult,
  type Ifrs9Result,
  type RegressionPoint,
  type RegressionResult,
} from "./hedge/hedge.js";
